#!/usr/bin/env python3
"""
coop init wizard — guided creation of .coop/project.yml.
Discovers what it can, asks only relevant integration questions, and emits a
minimal YAML contract without unused TODO sections.

Usage:
  lib/init_wizard.py <target-dir> [--template]

Without --template: run the guided wizard.
With --template: print the full documented example to stdout (legacy raw copy).
"""
import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, **kwargs)


def discover_git(cwd: Path) -> dict:
    info = {"root": "", "origin": "", "branch": "main", "user_name": "", "user_email": ""}
    try:
        p = run(["git", "rev-parse", "--show-toplevel"], cwd=cwd)
        if p.returncode == 0:
            info["root"] = p.stdout.strip()
        p = run(["git", "remote", "get-url", "origin"], cwd=cwd)
        if p.returncode == 0:
            info["origin"] = p.stdout.strip()
        for branch in ["main", "master"]:
            p = run(["git", "rev-parse", "--verify", branch], cwd=cwd)
            if p.returncode == 0:
                info["branch"] = branch
                break
        for key in ["user.name", "user.email"]:
            p = run(["git", "config", "--get", key], cwd=cwd)
            if p.returncode == 0:
                info[key.replace(".", "_")] = p.stdout.strip()
    except FileNotFoundError:
        pass
    return info


def discover_timezone() -> str:
    try:
        return datetime.now(timezone.utc).astimezone().tzname() or "UTC"
    except Exception:
        return "UTC"


def discover_tenant() -> str:
    # Try az account show, but do not fail if az is missing / not logged in.
    try:
        p = run(["az", "account", "show", "--output", "json"])
        if p.returncode == 0:
            data = json.loads(p.stdout)
            return data.get("tenantId", "")
    except Exception:
        pass
    return ""


def discover_te_path() -> str:
    # Tabular Editor 3 default Windows install path; empty if not found.
    candidates = [
        Path(os.environ.get("PROGRAMFILES", "C:/Program Files")) / "Tabular Editor 3" / "TabularEditor.exe",
        Path(os.environ.get("PROGRAMFILES(x86)", "C:/Program Files (x86)")) / "Tabular Editor 3" / "TabularEditor.exe",
    ]
    for c in candidates:
        if c.exists():
            return str(c)
    return ""


def read_input(prompt: str, default: str = "") -> str:
    sys.stderr.write(prompt)
    if default:
        sys.stderr.write(f" [{default}]")
    sys.stderr.write(": ")
    sys.stderr.flush()
    line = sys.stdin.readline()
    if not line:
        return default
    return line.strip() or default


def read_choice(prompt: str, choices: list[str], default: str = "") -> str:
    sys.stderr.write(prompt + "\n")
    for i, c in enumerate(choices, 1):
        mark = "*" if c == default else " "
        sys.stderr.write(f"  [{mark}] {i}. {c}\n")
    sys.stderr.write("> ")
    sys.stderr.flush()
    answer = sys.stdin.readline()
    if not answer:
        return default
    answer = answer.strip()
    if not answer:
        return default
    if answer.isdigit():
        idx = int(answer) - 1
        if 0 <= idx < len(choices):
            return choices[idx]
    lower = answer.lower()
    for c in choices:
        if c.lower() == lower:
            return c
    return default


def read_confirm(prompt: str, default: bool = False) -> bool:
    suffix = "Y/n" if default else "y/N"
    sys.stderr.write(f"{prompt} [{suffix}]: ")
    sys.stderr.flush()
    ans = sys.stdin.readline().strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes")


def indent(lines: list[str], spaces: int = 2) -> str:
    return "\n".join(" " * spaces + line for line in lines)


def quote(v: str) -> str:
    if not v:
        return '""'
    if re.search(r'[\s:\\\'"]', v):
        v = v.replace('"', '\\"')
        return f'"{v}"'
    return v


def ask_prefilled(prompt: str, default: str) -> str:
    v = read_input(prompt, default=default)
    return v


def build_project_yml(answers: dict) -> str:
    lines: list[str] = ["# Cooptimize agent — project contract (.coop/project.yml)", "# Generated by `coop init`", ""]
    lines.append("profile:")
    lines.append(f"  organization: {quote(answers['organization'])}")
    lines.append(f"  client: {quote(answers['client'])}")
    lines.append(f"  timezone: {quote(answers['timezone'])}")
    lines.append(f"  default_branch: {quote(answers['default_branch'])}")
    lines.append("  work_mode: consultant_review_first")
    lines.append("")

    lines.append("repositories:")
    lines.append(f"  {answers['repo_name']}:")
    lines.append(f"    description: {quote(answers['repo_description'])}")
    lines.append(f"    local_path: {quote(answers['repo_local_path'])}")
    lines.append(f"    remote_name: {quote(answers['repo_remote_name'])}")
    lines.append(f"    default_branch: {quote(answers['default_branch'])}")
    lines.append("    agent_allowed_to_commit:")
    lines.append("      - \"docs/**\"")
    lines.append("      - \"site/**\"")
    lines.append("      - \"docs/agent/logs/**\"")
    lines.append("      - \"docs/agent/diagrams/**\"")
    lines.append("    agent_never_commit:")
    lines.append("      - \"**/*.pbip\"")
    lines.append("      - \"**/*.pbir\"")
    lines.append("      - \"**/*.bim\"")
    lines.append("      - \"**/*.tmdl\"")
    lines.append("      - \"**/*.dax\"")
    lines.append("      - \"**/*.json\"")
    lines.append("      - \"**/*.rdl\"")
    lines.append("      - \"**/*.SemanticModel/**\"")
    lines.append("      - \"**/*.Report/**\"")
    lines.append("")

    if answers.get("use_fabric"):
        lines.append("fabric:")
        tenant = answers.get("tenant_id", "")
        lines.append(f"  tenant_id: {quote(tenant)}")
        lines.append("  default_workspace_name: \"\"")
        lines.append("  default_workspace_id: \"\"")
        lines.append("  lakehouse_names: []")
        lines.append("  warehouse_names: []")
        lines.append("  environment_names:")
        lines.append("    dev: \"\"")
        lines.append("    test: \"\"")
        lines.append("    prod: \"\"")
        lines.append("")

        lines.append("power_bi:")
        lines.append("  default_workspace_name: \"\"")
        lines.append("  default_workspace_id: \"\"")
        lines.append("  semantic_models: []")
        lines.append("  reports: []")
        lines.append("")

    lines.append("tools:")
    lines.append("  fabric_cli:")
    lines.append("    command: fab")
    lines.append(f"    enabled: {str(answers.get('use_fabric', False)).lower()}")
    lines.append("    default_mode: read_only_first")
    lines.append("  fabric_cicd:")
    lines.append("    library: fabric_cicd")
    lines.append("    injected_into: ms-fabric-cli")
    lines.append(f"    enabled: {str(answers.get('use_fabric', False)).lower()}")
    lines.append("    default_mode: validate_only")

    te_enabled = answers.get("use_tabular_editor", False)
    lines.append("  tabular_editor_cli:")
    lines.append(f"    enabled: {str(te_enabled).lower()}")
    if te_enabled:
        te_path = answers.get("te_path", "")
        lines.append(f"    executable_path: {quote(te_path)}")
        lines.append("    bpa_rules_path: \"\"")

    lines.append("  coop_data_doc:")
    lines.append("    command: coop-data-doc")
    lines.append("    enabled: true")
    lines.append("    default_command: build")
    lines.append("    machine_outputs: [\"graph.json\", \"manifest.json\"]")
    lines.append("  coop_sql_review:")
    lines.append("    command: coop-sql-review")
    lines.append("    enabled: true")
    lines.append("    invoke: \"check {paths} --format json\"")
    lines.append("    advisory_only: true")
    lines.append("  coop_dax_review:")
    lines.append("    command: coop-dax-review")
    lines.append("    enabled: true")
    lines.append("    invoke: \"check {paths} --format json\"")
    lines.append("    advisory_only: true")
    lines.append("")

    lines.append("mcp:")
    lines.append("  fabric:")
    lines.append(f"    enabled: {str(answers.get('use_fabric', False)).lower()}")
    lines.append("    allowed_default_actions: [\"list\", \"read\", \"inspect\"]")
    lines.append("    requires_approval_actions: [\"create\", \"update\", \"delete\", \"deploy\"]")
    lines.append("  powerbi:")
    lines.append(f"    enabled: {str(answers.get('use_fabric', False)).lower()}")
    lines.append("    readonly_flag: true")
    lines.append("    allowed_default_actions: [\"list\", \"read\", \"inspect\"]")
    lines.append("    requires_approval_actions: [\"create\", \"update\", \"delete\", \"publish\"]")
    lines.append("  microsoft_learn:")
    lines.append("    enabled: true")
    lines.append("    purpose: \"Always-current Microsoft documentation lookups\"")
    lines.append("  context_mode:")
    lines.append("    enabled: true")
    lines.append("")

    lines.append("memory:")
    lines.append("  extension: pi-hermes-memory")
    lines.append("  enabled: true")
    lines.append("  secret_scanning: true")
    lines.append("")

    lines.append("microsoft_skills:")
    lines.append("  source: \"https://github.com/microsoft/skills\"")
    lines.append("  load_dir: \"skills/_microsoft\"")
    lines.append("  allow:")
    lines.append("    - \"kql\"")
    lines.append("    - \"microsoft-docs\"")
    lines.append("")

    lines.append("fabric_skills:")
    lines.append("  source: \"https://github.com/microsoft/skills-for-fabric\"")
    lines.append("  load_dir: \"skills/_microsoft_fabric\"")
    lines.append("  allow: []")
    lines.append("")

    lines.append("standards:")
    lines.append("  sql: \"docs/standards/sql-standards.md\"")
    lines.append("  dax: \"docs/standards/dax-standards.md\"")
    lines.append("  documentation: \"docs/standards/documentation-standards.md\"")
    lines.append("  fabric: \"docs/standards/fabric-standards.md\"")
    lines.append("")

    lines.append("backup:")
    lines.append("  root: \".backups\"")
    lines.append("  timestamp_format: \"%Y%m%d_%H%M%S\"")
    lines.append("  naming_pattern: \"{original_name}.{timestamp}.bak\"")
    lines.append("  required_before_edit: true")
    lines.append("")

    lines.append("logging:")
    lines.append("  daily_log_path: \"docs/agent/logs/daily/{yyyy-mm-dd}.md\"")
    lines.append("  weekly_log_path: \"docs/agent/logs/weekly/{yyyy}-W{ww}.md\"")
    lines.append("  require_task_log: true")
    lines.append("")

    lines.append("documentation:")
    lines.append("  agent_docs_root: \"docs/agent\"")
    lines.append("  human_site_root: \"site\"")
    lines.append("  glossary_path: \"docs/agent/glossary/index.md\"")
    lines.append("  diagrams_path: \"docs/agent/diagrams\"")
    lines.append("  source_of_truth: \"markdown_first_html_generated\"")
    lines.append("  use_coop_data_doc: true")
    lines.append("")

    lines.append("workflow:")
    lines.append("  skill: \"coop-workflow\"")
    lines.append("  steps:")
    lines.append("    - \"Read .coop/project.yml + the relevant standards\"")
    lines.append("    - \"Identify repo/object + upstream/downstream impact; git status && git pull\"")
    lines.append("    - \"Read target file(s) + related docs/lineage (coop-data-doc)\"")
    lines.append("    - \"Write a short PLAN and get explicit review/approval before any edit\"")
    lines.append("    - \"Create a timestamped backup of every file to be changed\"")
    lines.append("    - \"Make the smallest safe edit\"")
    lines.append("    - \"Run the applicable review (coop-sql-review / coop-dax-review; Tabular Editor BPA / fabric-cicd validate where relevant)\"")
    lines.append("    - \"Show git diff + summarize the change\"")
    lines.append("    - \"Update Markdown docs / glossary / lineage; regenerate site if docs changed\"")
    lines.append("    - \"Append to the daily log\"")
    lines.append("    - \"Commit docs/logs/site ONLY with approval; never commit source\"")
    lines.append("")

    lines.append("approval_policy:")
    lines.append("  always_allowed:")
    lines.append("    - \"read files\"")
    lines.append("    - \"git status / git diff / git pull\"")
    lines.append("    - \"create backups\"")
    lines.append("    - \"run coop-sql-review / coop-dax-review / coop-data-doc (advisory)\"")
    lines.append("    - \"MCP list / read / inspect\"")
    lines.append("    - \"update markdown docs, html site, logs\"")
    lines.append("  ask_first:")
    lines.append("    - \"delete files\"")
    lines.append("    - \"fabric-cicd deploy / run deployment\"")
    lines.append("    - \"change production workspace\"")
    lines.append("    - \"commit documentation changes\"")
    lines.append("  never_without_explicit_instruction:")
    lines.append("    - \"commit SQL/DAX/model/report source changes\"")
    lines.append("    - \"push to remote\"")
    lines.append("    - \"deploy to test/prod\"")
    lines.append("    - \"MCP create/update/delete/deploy/publish\"")
    lines.append("    - \"delete Fabric / Power BI artifacts\"")
    lines.append("    - \"print secrets, tokens, connection strings, or .env contents\"")
    lines.append("")

    lines.append("tests:")
    lines.append("  live_data:")
    lines.append("    enabled: false")
    lines.append("    between_slices: true")
    lines.append("    command: \"\"")
    lines.append("    workspace: \"dev\"")
    lines.append("    require_approval: true")
    lines.append("")

    return "\n".join(lines)


def run_wizard(target_dir: Path) -> dict:
    sys.stderr.write("Let's set up your Cooptimize project contract.\n\n")
    cwd = target_dir.resolve()
    git = discover_git(cwd)

    repo_root = git.get("root") or str(cwd)
    repo_name = Path(repo_root).name or "repo"
    default_branch = git.get("branch") or "main"
    origin = git.get("origin") or ""
    user = git.get("user_name") or ""

    organization = ask_prefilled("Organization", "Cooptimize")
    client = ask_prefilled("Client / engagement", "")
    timezone = ask_prefilled("Timezone", discover_timezone())

    repo_name = ask_prefilled("Repository short name", repo_name)
    repo_description = ask_prefilled("Repository description", "Project source and docs")
    repo_local_path = ask_prefilled("Repository local path", repo_root)
    default_branch = ask_prefilled("Default branch", default_branch)

    use_fabric = read_confirm("Is this a Microsoft Fabric / Power BI engagement?", default=False)
    tenant_id = ""
    if use_fabric:
        tenant_id = ask_prefilled("Azure tenant ID (optional)", discover_tenant())

    use_tabular_editor = False
    te_path = ""
    if sys.platform == "win32":
        use_tabular_editor = read_confirm("Use Tabular Editor 3 for BPA rules?", default=False)
        if use_tabular_editor:
            te_path = ask_prefilled("Tabular Editor 3 executable path", discover_te_path())

    setup_lineage = read_confirm("Configure SQL + Power BI lineage docs now? (runs `coop-data-doc setup`)", default=False)

    return {
        "organization": organization,
        "client": client,
        "timezone": timezone,
        "default_branch": default_branch,
        "repo_name": repo_name,
        "repo_description": repo_description,
        "repo_local_path": repo_local_path,
        "repo_remote_name": "origin",
        "use_fabric": use_fabric,
        "tenant_id": tenant_id,
        "use_tabular_editor": use_tabular_editor,
        "te_path": te_path,
        "setup_lineage": setup_lineage,
    }


def run_lineage_setup(target: Path) -> None:
    """The user accepted the lineage-docs offer: run the coop-data-doc wizard.

    Inherits the terminal (no capture) so coop-data-doc's questionary prompts
    render; a missing binary or non-TTY run degrades to a friendly hint.
    """
    sys.stderr.write("\nLaunching coop-data-doc setup (Ctrl-C to skip)…\n")
    try:
        cmd = os.environ.get("COOP_DATA_DOC_BIN", "coop-data-doc")
        # On Windows, .bat/.cmd files can't be executed via CreateProcess directly;
        # route them through cmd.exe so PATH/PATHEXT resolution isn't needed.
        if sys.platform == "win32" and cmd.lower().endswith((".bat", ".cmd")):
            subprocess.run(["cmd.exe", "/c", cmd, "setup"], cwd=target)
        else:
            subprocess.run([cmd, "setup"], cwd=target)
    except FileNotFoundError:
        sys.stderr.write("coop-data-doc isn't installed — run `coop install`, then `coop data-doc setup`.\n")
    except Exception as exc:
        sys.stderr.write(f"coop-data-doc setup failed ({exc}). Run `coop data-doc setup` anytime.\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Cooptimize project init wizard.")
    parser.add_argument("target_dir", help="Directory to create .coop/project.yml in.")
    parser.add_argument("--template", action="store_true", help="Print the full legacy template instead of running the wizard.")
    args = parser.parse_args(argv)

    script_dir = Path(__file__).resolve().parent
    example = script_dir.parent / ".coop" / "project.example.yml"

    if args.template:
        if example.exists():
            print(example.read_text(encoding="utf-8"), end="")
        else:
            sys.stderr.write("Template not found.\n")
            return 1
        return 0

    target = Path(args.target_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)
    coop_dir = target / ".coop"
    coop_dir.mkdir(exist_ok=True)
    dst = coop_dir / "project.yml"

    if dst.exists():
        sys.stderr.write(f"{dst} already exists — not overwriting.\n")
        return 1

    answers = run_wizard(target)
    yml = build_project_yml(answers)
    dst.write_text(yml, encoding="utf-8")
    sys.stderr.write(f"\nWrote {dst}\n")
    sys.stderr.write("Review it, then run: coop doctor\n")
    if answers.get("setup_lineage"):
        run_lineage_setup(target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
